#!/usr/bin/env node
/**
 * Collapse the `dist-preview` build into a single, double-clickable preview.html
 * at the project root.
 *
 * vite.preview.config.js has already done the hard part: every image is a data:
 * URI, there is exactly one stylesheet, and the bundle is a classic IIFE rather
 * than an ES module (inline modules are unreliable over file://). All that is
 * left is to fold the two emitted files into the HTML and drop the throwaway
 * output directory.
 *
 * Remote <link>s — the Google Fonts stylesheet — are deliberately left alone.
 * Orbitron is not bundled, so the file still wants a network connection for
 * type; everything else works offline.
 *
 * Run with `npm run build:preview`.
 */
import { readFileSync, writeFileSync, rmSync, existsSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "dist-preview");
const entry = join(outDir, "index.html");

if (!existsSync(entry)) {
  console.error(
    "dist-preview/index.html not found — run `vite build --config vite.preview.config.js` first.",
  );
  process.exit(1);
}

const read = (href) => readFileSync(join(outDir, href.replace(/^\//, "")), "utf8");
const isLocal = (href) => href && !/^(https?:)?\/\//.test(href) && !href.startsWith("data:");
const attr = (tag, name) => tag.match(new RegExp(`${name}="([^"]*)"`))?.[1];

let html = readFileSync(entry, "utf8");
let inlinedCss = 0;
let inlinedJs = 0;

// Stylesheets. Only local ones — the Google Fonts link must stay a link.
html = html.replace(/<link\b[^>]*>/g, (tag) => {
  const href = attr(tag, "href");
  if (!/rel="stylesheet"/.test(tag) || !isLocal(href)) return tag;
  inlinedCss++;
  return `<style>\n${read(href).trim()}\n</style>`;
});

// Scripts with a src. Vite emits these into <head>, relying on type="module"
// being deferred. Our bundle is a classic IIFE, which would instead run
// synchronously in <head> — before #root exists — so React's createRoot fails
// with error #299 and the page renders blank. Lift the code out here and
// re-attach it at the end of <body>, where it is guaranteed a mounted DOM.
const bundles = [];
html = html.replace(/<script\b[^>]*\bsrc="[^"]*"[^>]*>\s*<\/script>/g, (tag) => {
  const src = attr(tag, "src");
  if (!isLocal(src)) return tag;
  inlinedJs++;
  bundles.push(read(src).trim());
  return "";
});

if (!inlinedCss || !inlinedJs) {
  console.error(
    `expected to inline at least one stylesheet and one script, got css=${inlinedCss} js=${inlinedJs}`,
  );
  process.exit(1);
}

html = html.replace(
  /<\/body>/,
  `${bundles.map((js) => `<script>\n${js}\n</script>`).join("\n")}\n</body>`,
);

html = html.replace(
  /<head>/,
  `<head>\n    <!-- Generated by \`npm run build:preview\` — do not edit by hand. -->\n` +
    `    <meta http-equiv="Cache-Control" content="no-store" />`,
);

const dest = join(root, "preview.html");
writeFileSync(dest, html);
rmSync(outDir, { recursive: true, force: true });

const mb = (statSync(dest).size / 1024 / 1024).toFixed(2);
const remaining = [...html.matchAll(/(?:src|href)="(?!data:|#)([^"]+)"/g)]
  .map((m) => m[1])
  .filter((u) => !/^https?:/.test(u));

console.log(`preview.html  ${mb} MB  (${inlinedCss} stylesheet, ${inlinedJs} script inlined)`);
if (remaining.length) {
  console.error(`not self-contained — unresolved local refs: ${remaining.join(", ")}`);
  process.exit(1);
}
